# Create the ecmean development environment:
# mamba env create -f dev-environment.yml
# or
# conda env create -f dev-environment.yml

name : ecmean-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.15
  - libnetcdf
  - xesmf
  - cdo
  - ncview
  - ipykernel
  - pip
  - pip:
    - -e .[all]
