[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ecmean"
dynamic = ["version"]
authors = [
  { name="Paolo Davini", email="paolo.davini@cnr.it" },
  { name="Jost von Hardenberg", email="jost.hardenberg@polito.it" } 
]
description = "A Global Climate Model lightweight evaluation tool"
readme = "README.md"
requires-python = ">=3.9,<=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
keywords = ["climate", "evaluation", "EC-Earth", "climate-model", "diagnostics", "performance-indices", "global-mean"]
dependencies = [
    "xarray",
    "numpy",
    "netcdf4",
    "numba",
    "dask",
    "esmpy",
    "xesmf",
    "metpy",
    "matplotlib",
    "tabulate",
    "cfgrib",
    "seaborn"
]

[project.optional-dependencies]
tests = [
    "flake8",
    "pytest",
    "coverage",
    "coveralls".
    "statsmodels"
]

docs = [
    "sphinx<7.0",
    "sphinx-rtd-theme"
]

all = [
    "ecmean[tests,docs]"
]

[project.urls]
"Homepage" = "https://github.com/oloapinivad/ecmean"
"Repository" = "https://github.com/oloapinivad/ecmean"
"Documentation" = "https://ecmean.readthedocs.io/en/latest/"
"Bug Tracker" = "https://github.com/oloapinivad/ecmean/issues"


[project.scripts]
global_mean = "ecmean.global_mean:gm_entry_point"
performance_indices = "ecmean.performance_indices:pi_entry_point"

[tool.setuptools.dynamic]
version = {attr = "ecmean.__version__"}

[tool.coverage.run]
concurrency = ["multiprocessing"]
source = ["ecmean"]
omit = [
    "*/tests/*",
    "*/test_*.py",
]

[tool.coverage.report]
ignore_errors = true

[tool.coverage.paths]
source = [
    "ecmean/",
    "*/ecmean/",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

