# Choice of model name, determines the chosen interface and is printed in the output table
interface: CMIP6_esgpull
model:
   name: EC-Earth3

dirs:
   exp: /archive/paolo/esgpull
   tab: /work/scratch/users/paolo/ecmean_cmip6
   fig: /work/users/paolo/figures/ECmean4

global:
  atm_vars: [tas, psl, pr, evspsbl, pme, clt, cll, clm, clh,
             pr_oce, pme_oce, pr_land, pme_land,
             net_toa, rsnt, rlnt, rsntcs, rlntcs, swcf, lwcf,
             rsns, rlns, hfss, hfls, net_sfc_nosn, net_sfc,
             toamsfc_nosn, toamsfc]
  ice_vars: [siconc, siconc_north, siconc_south]
  oce_vars: [tos, sos, zos, wfo]
  tab_vars: [rsnt, rlnt, net_toa, rsns, rlns, hfss, hfls, swcf, lwcf, net_sfc, toamsfc, tas, clt, cll, clm, clh, pr, pme, psl]
  regions: ['Global', 'Tropical', 'North Midlat', 'South Midlat']
  seasons: ['ALL', 'DJF', 'JJA']


PI:
  2d_vars:
    field: [tas, pr, psl, tauu, tauv, net_sfc]
  3d_vars:
    field: [ua, va, ta, hus]
  oce_vars:
    field: [tos, sos]
  ice_vars:
    field: [siconc]
  regions: ['Global', 'Tropical', 'North Midlat', 'South Midlat', 'NH', 'SH', 'Equatorial', 'North Pole', 'South Pole']
  seasons: ['ALL', 'DJF', 'JJA']
  resolution: r360x180
